FizzBuzz/Controllers/FizzBuzzController.cs
namespace FizzBuzz.Controllers
{
    using System.Threading.Tasks;
    using FizzBuzz.CQRS;
    using FizzBuzz.Model;
    using MediatR;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    public class FizzBuzzController : Controller
    {
        private readonly IMediator _mediator;

        public FizzBuzzController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(FizzBuzzViewModel model)
        {
            if (ModelState.IsValid)
            {
                var fizzbuzz = new ProcessFizzBuzz.Context(model.Number ?? 0);
                var response = await _mediator.Send(fizzbuzz);                
                model.Results = response.Results.ToPagedList(1, 20);
                return View(model);
            }
            return View();
        }

        public async Task<IActionResult> FizzBuzz(FizzBuzzViewModel model)
        {
            var fizzbuzz = new ProcessFizzBuzz.Context(model.Number ?? 0);
            var pagenumber = model.Page ?? 1;
            var response = await _mediator.Send(fizzbuzz);            
            model.Results = response.Results.ToPagedList(pagenumber, 20);
            return View("Index", model);
        }
    }
}

FizzBuzz/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Model.FizzBuzzViewModel

@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common;
 

<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
<link href="~/css/Style.css" rel="stylesheet" />

<div class="container body-content">
    @using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Post))
    {        
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6 col-sm-12">
                        <div class="row form-group">

                            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "col-lg-2 col-sm-12 col-form-label label-left" })
                            <div class="col-lg-7 col-sm-12">
                                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-12">
                        <div class="row form-group">
                            <div class="col-lg-7 col-sm-12">
                                <input type="submit" value="Show" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @if (Model != null && Model.Results.Count() > 0)
            {
                <div class="table-responsive" id="viewTable">

                    <table class="table table-bordered" id="ViewComponentsec">
                        <thead>
                            <tr>
                                <th>Numbers</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Results.Select((x, i) => new { Data = x, Index = i + 1 }))
                            {
                                <tr>
                                    <td>
                                        @foreach (var text in item.Data.Split(' '))
                                        {
                                            <span class=@text>
                                                @Html.DisplayFor(model => text)
                                            </span>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>

                <div>
                    @Html.PagedListPager((IPagedList)Model.Results, page => Url.Action("FizzBuzz", new FizzBuzz.Model.FizzBuzzViewModel { Number = Model.Number, Page = page }), PagedListRenderOptions.Classic)
                </div>
            }
        }
    </div>